### ISSUE TITLE
Reentrancy checks

### ISSUE THREAD

**Issue by flygoing** [ZeframLou/pooled-cdai#1]
Is the reentrancy protection necessary in the `mint` and `burn` functions? It adds a non-negligible amount of gas, and the only external calls are to `dai` and `cdai`, unless I'm missing something. Unless cDAI somehow allows arbitrary calls from inside its functions, I don't think the protection is necessary.

**Comment by ZeframLou** [comment]
Technically even `dai` and `cdai` can't be trusted, but practically you're right. I'll remove the checks.
